// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Connect to Finger server and fetch content
Future<String> connectAndFetchFinger({
  required String host,
  required int port,
  required String username,
}) => RustLib.instance.api.crateApiProtocolsFingerConnectAndFetchFinger(
  host: host,
  port: port,
  username: username,
);
