// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connect_and_fetch_gemini`, `connect_and_fetch_gopher`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Navigate to a Gemini or Gopher URL and return the plaintext content
Future<String> navigate({required String url}) =>
    RustLib.instance.api.crateApiSimpleNavigate(url: url);

/// Get the default start page URL
String getStartPage() => RustLib.instance.api.crateApiSimpleGetStartPage();
